apiVersion: v1
kind: Secret
metadata:
  name: moni-secrets
type: Opaque
data:
  JWT_SECRET: ${BASE64_JWT_SECRET}
  POSTGRES_PASSWORD: ${BASE64_POSTGRES_PASSWORD}
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}
  RABBITMQ_USER: ${BASE64_RABBITMQ_USER}
  RABBITMQ_PASSWORD: ${BASE64_RABBITMQ_PASSWORD}
  SMTP_PASSWORD: ${BASE64_SMTP_PASSWORD}

